name: skillexchange

services:
  backend:
    build: .
    container_name: skillexchange_api
    ports: ["9081:9081"]
    env_file:
      - .env.${ENV_STAGE:-qa}
    depends_on: [mysql-db, mongodb, localstack]
    networks: [se-network]
    restart: on-failure

  mongodb:
    volumes:
      - mongo_data_${ENV_STAGE:-qa}:/data/db
      - ./docker/mongo/init/001-create-app-user.js:/docker-entrypoint-initdb.d/001-create-app-user.js:ro
    env_file:
      - .env.mongo.${ENV_STAGE:-qa}
    networks: [se-network]
