name: skillexchange

services:
  backend:
    build: .
    container_name: skillexchange_api
    ports: ["9081:9081"]
    env_file:
      - .env.${ENV_STAGE:-prod}
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9081/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
